# Generated by Django 5.1.5 on 2025-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(help_text='Styl tańca (np. Salsa, Waltz)', max_length=100)),
                ('max_participants', models.PositiveIntegerField(help_text='Maksymalna liczba uczestników')),
                ('instructor', models.CharField(help_text='Imię i nazwisko nauczyciela', max_length=200)),
                ('start_time', models.DateTimeField(help_text='Data i czas rozpoczęcia zajęć')),
                ('end_time', models.DateTimeField(help_text='Data i czas zakończenia zajęć')),
                ('room', models.CharField(blank=True, help_text='Sala zajęciowa', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Imię instruktora', max_length=50)),
                ('last_name', models.CharField(help_text='Nazwisko instruktora', max_length=50)),
                ('email', models.EmailField(help_text='E-mail kontaktowy', max_length=254, unique=True)),
                ('specialization', models.CharField(blank=True, help_text='Specjalizacja (np. Salsa, Tango)', max_length=100)),
            ],
        ),
    ]
