# Generated by Django 5.1.5 on 2025-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Dni tygodnia (np. MO,WE,FR)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end_hour',
            field=models.TimeField(blank=True, help_text='Godzina zakończenia zajęć', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Czy zajęcia są cykliczne'),
        ),
        migrations.AddField(
            model_name='class',
            name='start_hour',
            field=models.TimeField(blank=True, help_text='Godzina rozpoczęcia zajęć', null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Data i czas zakończenia zajęć', null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Data i czas rozpoczęcia zajęć', null=True),
        ),
    ]
