# Generated by Django 5.1.5 on 2025-02-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_class_days_of_week_class_end_hour_class_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_hour',
        ),
        migrations.AlterField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Dni tygodnia dla zajęć cyklicznych (np. MO,WE,FR)', max_length=20, null=True),
        ),
    ]
