# Generated by Django 5.1.5 on 2025-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_class_end_hour_remove_class_start_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Dni tygodnia dla zajęć cyklicznych (np. MO,WE,FR)', max_length=100, null=True),
        ),
    ]
