# Generated by Django 5.1.5 on 2025-02-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_class_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('single', 'Pojedyncze zajęcia'), ('monthly', 'Karnet miesięczny'), ('quarterly', 'Karnet kwartalny'), ('yearly', 'Karnet roczny')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('completed', 'Zrealizowana'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
