# Generated by Django 5.1.5 on 2025-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Gotówka'), ('transfer', 'Przelew bankowy'), ('blik', 'BLIK'), ('card', 'Karta płatnicza w studio')], default='transfer', max_length=20),
        ),
    ]
