# Generated by Django 5.1.5 on 2025-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_recipient', models.CharField(max_length=200)),
                ('blik_number', models.CharField(blank=True, max_length=20)),
                ('transfer_title_prefix', models.CharField(default='Płatność - ', max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
